### PR TITLE
Student assignment chris

### PR DESCRIPTION
**Pull request by ChristopherPHolder**
Created Teacher > Assignment > Grading

Corrected styling from the Assignment Menus

### CODE REVIEW

**Comment by ChristopherPHolder** [comment]
Created Teacher > Assignment > Grading

Corrected styling from the Assignment Menus

**Comment by ChristopherPHolder** [comment]
Closing pull request due to additional changes. 
Adding Scss variables for reusable styles!

**Comment by fuelupeducation** [comment]
Reopen

**Comment by fuelupeducation** [comment]
Merged

**Pull request closed without merging**
